import { motion } from 'framer-motion'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Play, Pause, Music2 } from 'lucide-react'
import { cn } from '@/lib/utils'

interface DemoTrack {
  title: string
  style: string
  model: string
  duration: string
  src: string
}

/**
 * Audio Demos Section
 *
 * Showcases real AI-generated music samples on the landing page.
 * Each card plays an MP3 from public/audio/ using HTML5 <audio>.
 * Only one track plays at a time (previous track pauses when a new one starts).
 */
const demoTracks: DemoTrack[] = [
  {
    title: 'New Habits',
    style: 'Indie Pop / Acoustic',
    model: 'ElevenLabs',
    duration: '0:30',
    src: '/audio/demo-new-habits.mp3',
  },
  {
    title: 'Golden Hour',
    style: 'Lo-fi / Chill',
    model: 'MiniMax',
    duration: '0:34',
    src: '/audio/demo-golden-hour.mp3',
  },
  {
    title: 'Rise Above',
    style: 'Cinematic / Inspirational',
    model: 'MiniMax',
    duration: '1:06',
    src: '/audio/demo-rise-above.mp3',
  },
]

// Custom event to coordinate playback across cards — only one plays at a time
const PAUSE_ALL_EVENT = 'demo-pause-all'

export function AudioDemosSection() {
  return (
    <section id="demos" className="py-24 lg:py-32">
      <div className="container mx-auto px-4 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">
            Hear what's possible
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Every track below was generated by AI. Choose your style, write a
            prompt, and create music in seconds.
          </p>
        </motion.div>

        {/* Demo Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 max-w-4xl mx-auto">
          {demoTracks.map((track, index) => (
            <motion.div
              key={track.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
            >
              <DemoCard track={track} />
            </motion.div>
          ))}
        </div>

        {/* Subtle note */}
        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="text-center text-sm text-muted-foreground mt-10"
        >
          All samples generated using Songlar with ElevenLabs and MiniMax
          models.
        </motion.p>
      </div>
    </section>
  )
}

function DemoCard({ track }: { track: DemoTrack }) {
  const [isPlaying, setIsPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [displayDuration, setDisplayDuration] = useState(track.duration)
  const audioRef = useRef<HTMLAudioElement>(null)
  const instanceId = useRef(Math.random().toString(36).slice(2))

  // Listen for the "pause all" event from other cards
  useEffect(() => {
    function handlePauseAll(e: Event) {
      const detail = (e as CustomEvent).detail
      if (detail !== instanceId.current && audioRef.current) {
        audioRef.current.pause()
        setIsPlaying(false)
      }
    }

    window.addEventListener(PAUSE_ALL_EVENT, handlePauseAll)
    return () => window.removeEventListener(PAUSE_ALL_EVENT, handlePauseAll)
  }, [])

  // When the audio metadata loads, update the displayed duration
  const handleLoadedMetadata = useCallback(() => {
    const audio = audioRef.current
    if (audio && isFinite(audio.duration)) {
      const mins = Math.floor(audio.duration / 60)
      const secs = Math.floor(audio.duration % 60)
      setDisplayDuration(`${mins}:${secs.toString().padStart(2, '0')}`)
    }
  }, [])

  const togglePlay = useCallback(() => {
    const audio = audioRef.current
    if (!audio) return

    if (isPlaying) {
      audio.pause()
      setIsPlaying(false)
    } else {
      // Pause all other playing cards first
      window.dispatchEvent(
        new CustomEvent(PAUSE_ALL_EVENT, { detail: instanceId.current }),
      )
      audio.play().catch(() => {
        // Autoplay may be blocked — silently ignore
      })
      setIsPlaying(true)
    }
  }, [isPlaying])

  const handleTimeUpdate = useCallback(() => {
    const audio = audioRef.current
    if (audio && audio.duration) {
      setProgress((audio.currentTime / audio.duration) * 100)
    }
  }, [])

  const handleEnded = useCallback(() => {
    setIsPlaying(false)
    setProgress(0)
  }, [])

  return (
    <div className="group relative rounded-xl border bg-card p-5 transition-all duration-300 hover:shadow-md hover:-translate-y-0.5">
      {/* Hidden audio element */}
      <audio
        ref={audioRef}
        src={track.src}
        preload="metadata"
        onTimeUpdate={handleTimeUpdate}
        onEnded={handleEnded}
        onLoadedMetadata={handleLoadedMetadata}
      />

      {/* Waveform Visualization */}
      <div className="relative mb-4 h-20 flex items-center justify-center rounded-lg bg-muted/50 overflow-hidden">
        {/* Progress background fill */}
        <div
          className="absolute inset-0 bg-primary/10 transition-all duration-150 ease-linear origin-left"
          style={{ width: `${progress}%` }}
        />

        {/* Decorative waveform bars */}
        <div className="relative flex items-center gap-[3px] h-12">
          {Array.from({ length: 24 }).map((_, i) => {
            const height = Math.sin((i / 24) * Math.PI) * 0.7 + 0.3
            const barProgress = (i / 24) * 100
            const isPastPlayhead = barProgress < progress

            return (
              <div
                key={i}
                className={cn(
                  'w-[3px] rounded-full transition-all duration-300',
                  isPlaying && isPastPlayhead
                    ? 'bg-primary'
                    : isPlaying
                      ? 'bg-primary/40'
                      : 'bg-primary/30 group-hover:bg-primary/50',
                )}
                style={{
                  height: `${height * 100}%`,
                }}
              />
            )
          })}
        </div>

        {/* Play/Pause overlay */}
        <button
          onClick={togglePlay}
          className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-background/50 backdrop-blur-sm cursor-pointer"
        >
          <div className="flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground shadow-lg">
            {isPlaying ? (
              <Pause className="h-4 w-4" />
            ) : (
              <Play className="h-4 w-4 ml-0.5" />
            )}
          </div>
        </button>
      </div>

      {/* Track Info */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <h4 className="font-semibold text-sm">{track.title}</h4>
          <span className="text-xs text-muted-foreground font-mono">
            {displayDuration}
          </span>
        </div>
        <p className="text-xs text-muted-foreground">{track.style}</p>
        <div className="flex items-center gap-1.5">
          <Music2 className="h-3 w-3 text-muted-foreground" />
          <span className="text-xs text-muted-foreground">{track.model}</span>
        </div>
      </div>
    </div>
  )
}
