import { motion } from 'framer-motion'
import { useState } from 'react'
import { Play, Pause, Music2 } from 'lucide-react'
import { cn } from '@/lib/utils'

interface DemoTrack {
  title: string
  style: string
  model: string
  duration: string
}

/**
 * Audio Demos Section
 *
 * Showcases what AI-generated music sounds like.
 * Uses placeholder demo cards (no actual audio files yet — these can be
 * swapped for real samples later by adding `src` to DemoTrack and wiring
 * up the <audio> element).
 */
const demoTracks: DemoTrack[] = [
  {
    title: 'Neon Dreams',
    style: 'Synthwave / Electronic',
    model: 'ElevenLabs',
    duration: '0:32',
  },
  {
    title: 'Golden Hour',
    style: 'Lo-fi / Chill',
    model: 'MiniMax',
    duration: '0:28',
  },
  {
    title: 'Rise Above',
    style: 'Cinematic / Orchestral',
    model: 'ElevenLabs',
    duration: '0:35',
  },
  {
    title: 'Street Lights',
    style: 'Hip-Hop / Beat',
    model: 'MiniMax',
    duration: '0:30',
  },
]

export function AudioDemosSection() {
  return (
    <section id="demos" className="py-24 lg:py-32">
      <div className="container mx-auto px-4 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">
            Hear what's possible
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Every track below was generated by AI. Choose your style, write a
            prompt, and create music in seconds.
          </p>
        </motion.div>

        {/* Demo Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 max-w-5xl mx-auto">
          {demoTracks.map((track, index) => (
            <motion.div
              key={track.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
            >
              <DemoCard track={track} />
            </motion.div>
          ))}
        </div>

        {/* Subtle note */}
        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="text-center text-sm text-muted-foreground mt-10"
        >
          All samples generated using Songlar with ElevenLabs and MiniMax
          models.
        </motion.p>
      </div>
    </section>
  )
}

function DemoCard({ track }: { track: DemoTrack }) {
  const [isPlaying, setIsPlaying] = useState(false)

  return (
    <div className="group relative rounded-xl border bg-card p-5 transition-all duration-300 hover:shadow-md hover:-translate-y-0.5">
      {/* Waveform Visualization (decorative) */}
      <div className="relative mb-4 h-20 flex items-center justify-center rounded-lg bg-muted/50 overflow-hidden">
        {/* Decorative waveform bars */}
        <div className="flex items-center gap-[3px] h-12">
          {Array.from({ length: 24 }).map((_, i) => {
            const height = Math.sin((i / 24) * Math.PI) * 0.7 + 0.3
            return (
              <div
                key={i}
                className={cn(
                  'w-[3px] rounded-full transition-all duration-300',
                  isPlaying
                    ? 'bg-primary animate-pulse'
                    : 'bg-primary/30 group-hover:bg-primary/50',
                )}
                style={{
                  height: `${height * 100}%`,
                  animationDelay: isPlaying ? `${i * 50}ms` : undefined,
                }}
              />
            )
          })}
        </div>

        {/* Play/Pause overlay */}
        <button
          onClick={() => setIsPlaying(!isPlaying)}
          className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-background/50 backdrop-blur-sm cursor-pointer"
        >
          <div className="flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground shadow-lg">
            {isPlaying ? (
              <Pause className="h-4 w-4" />
            ) : (
              <Play className="h-4 w-4 ml-0.5" />
            )}
          </div>
        </button>
      </div>

      {/* Track Info */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <h4 className="font-semibold text-sm">{track.title}</h4>
          <span className="text-xs text-muted-foreground font-mono">
            {track.duration}
          </span>
        </div>
        <p className="text-xs text-muted-foreground">{track.style}</p>
        <div className="flex items-center gap-1.5">
          <Music2 className="h-3 w-3 text-muted-foreground" />
          <span className="text-xs text-muted-foreground">{track.model}</span>
        </div>
      </div>
    </div>
  )
}
